version: "3.9"

services:

  # app:
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile
  #   restart: always
  #   ports: 
  #     - "8080:8080"
  #   env_file:
  #     - app.env
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #       restart: true
  #   volumes:
  #     - ./app.env:/app/app.env

  db:
    image: 'postgres'
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bank
    volumes:
      - data:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: pg_isready -U postgres
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  data: