version: "3.9"

services:

  db:
    image: 'postgres'
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASWORD: password
      POSTGRES_DB: bank
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/