// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: account.sql

package db

import (
	"context"
	"time"
)

const addBalanceToAccount = `-- name: AddBalanceToAccount :one
UPDATE accounts SET balance = balance + $1
WHERE id = $2
RETURNING id, owner, balance, currency, created_at, user_id
`

type AddBalanceToAccountParams struct {
	Amount int64 `json:"amount"`
	ID     int64 `json:"id"`
}

func (q *Queries) AddBalanceToAccount(ctx context.Context, arg AddBalanceToAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, addBalanceToAccount, arg.Amount, arg.ID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
		&i.UserID,
	)
	return i, err
}

const createAccount = `-- name: CreateAccount :exec
INSERT INTO accounts (owner,
                      user_id,
                      balance,
                      currency, 
                      created_at)
VALUES ($1, $2, $3, 'USD', $4), ($1, $2, $3, 'EUR', $4), ($1, $2, $3, 'UAH', $4),
	   ($1, $2, $3, 'RUB', $4), ($1, $2, $3, 'CHN', $4), ($1, $2, $3, 'QWE', $4),
	   ($1, $2, $3, 'WER', $4), ($1, $2, $3, 'ERT', $4), ($1, $2, $3, 'RTY', $4),
	   ($1, $2, $3, 'TYU', $4), ($1, $2, $3, 'YUI', $4), ($1, $2, $3, 'UIO', $4),
	   ($1, $2, $3, 'IOP', $4), ($1, $2, $3, 'ASD', $4), ($1, $2, $3, 'SDF', $4),
	   ($1, $2, $3, 'DFG', $4), ($1, $2, $3, 'FGH', $4), ($1, $2, $3, 'GHJ', $4)
`

type CreateAccountParams struct {
	Owner     string    `json:"owner"`
	UserID    int64     `json:"user_id"`
	Balance   int64     `json:"balance"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) error {
	_, err := q.db.ExecContext(ctx, createAccount,
		arg.Owner,
		arg.UserID,
		arg.Balance,
		arg.CreatedAt,
	)
	return err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM accounts WHERE id = $1
`

func (q *Queries) DeleteAccount(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAccount, id)
	return err
}

const getAccount = `-- name: GetAccount :one
SELECT id, owner, balance, currency, created_at, user_id
FROM accounts
WHERE id = $1
`

func (q *Queries) GetAccount(ctx context.Context, id int64) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
		&i.UserID,
	)
	return i, err
}

const getAccountForUpdate = `-- name: GetAccountForUpdate :one
SELECT id, owner, balance, currency, created_at, user_id
FROM accounts
WHERE user_id = $1 and id = $2
FOR NO KEY UPDATE
`

type GetAccountForUpdateParams struct {
	UserID int64 `json:"user_id"`
	ID     int64 `json:"id"`
}

func (q *Queries) GetAccountForUpdate(ctx context.Context, arg GetAccountForUpdateParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountForUpdate, arg.UserID, arg.ID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
		&i.UserID,
	)
	return i, err
}

const getUserAccount = `-- name: GetUserAccount :one
SELECT id, owner, balance, currency, created_at, user_id
FROM accounts
WHERE user_id = $1 and id = $2
`

type GetUserAccountParams struct {
	UserID int64 `json:"user_id"`
	ID     int64 `json:"id"`
}

func (q *Queries) GetUserAccount(ctx context.Context, arg GetUserAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, getUserAccount, arg.UserID, arg.ID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
		&i.UserID,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, owner, balance, currency, created_at, user_id
FROM accounts
WHERE user_id = $1
ORDER BY id DESC
LIMIT $2 OFFSET $3
`

type ListAccountsParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, listAccounts, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Balance,
			&i.Currency,
			&i.CreatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE accounts SET balance = $2
WHERE id = $1
RETURNING id, owner, balance, currency, created_at, user_id
`

type UpdateAccountParams struct {
	ID      int64 `json:"id"`
	Balance int64 `json:"balance"`
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, updateAccount, arg.ID, arg.Balance)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
		&i.UserID,
	)
	return i, err
}
