// Code generated by MockGen. DO NOT EDIT.
// Source: bank/async (interfaces: TaskDistributor)
//
// Generated by this command:
//
//	mockgen -package async -destination async/mock/distributor.go bank/async TaskDistributor
//

// Package async is a generated GoMock package.
package async

import (
	async "bank/async"
	context "context"
	reflect "reflect"

	asynq "github.com/hibiken/asynq"
	gomock "go.uber.org/mock/gomock"
)

// MockTaskDistributor is a mock of TaskDistributor interface.
type MockTaskDistributor struct {
	ctrl     *gomock.Controller
	recorder *MockTaskDistributorMockRecorder
}

// MockTaskDistributorMockRecorder is the mock recorder for MockTaskDistributor.
type MockTaskDistributorMockRecorder struct {
	mock *MockTaskDistributor
}

// NewMockTaskDistributor creates a new mock instance.
func NewMockTaskDistributor(ctrl *gomock.Controller) *MockTaskDistributor {
	mock := &MockTaskDistributor{ctrl: ctrl}
	mock.recorder = &MockTaskDistributorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskDistributor) EXPECT() *MockTaskDistributorMockRecorder {
	return m.recorder
}

// DistributeTaskVerifyEmail mocks base method.
func (m *MockTaskDistributor) DistributeTaskVerifyEmail(arg0 context.Context, arg1 *async.PayloadSendVerifyEmail, arg2 ...asynq.Option) error {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DistributeTaskVerifyEmail", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// DistributeTaskVerifyEmail indicates an expected call of DistributeTaskVerifyEmail.
func (mr *MockTaskDistributorMockRecorder) DistributeTaskVerifyEmail(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DistributeTaskVerifyEmail", reflect.TypeOf((*MockTaskDistributor)(nil).DistributeTaskVerifyEmail), varargs...)
}
